Lab1
Dross0/Network-Labs pull request #2
Opened 2020-09-24 17:07 UTC by Dross0

@Aloomenon

2020-09-25 08:30 UTC, Aloomenon requested changes
Ну смотрите сами, что закидываете. Это ведь не сложно блин.

2020-09-25 08:33 UTC, Aloomenon commented
В любом случае посмотрел по удалённому. Освобождайте ща собой ресурсы, как минимум.

2020-09-25 08:35 UTC, Dross0 commented
У меня советы закрываются

2020-09-25 08:36 UTC, Aloomenon commented
Продемонстрируйте

2020-09-25 08:37 UTC, Dross0 commented
При IOException сокета закрываются

2020-09-25 09:06 UTC, Dross0 commented
@Aloomenon Добавил try with resources

2020-09-25 10:27 UTC, Aloomenon commented
Что будет с сокетами, если экстренно завершить работу приложения?

2020-09-25 10:28 UTC, Aloomenon requested changes
Что будет, если в конфигурации не будет данных или они будут кривыми?

2020-09-25 10:29 UTC, Aloomenon submitted a review, later dismissed

2020-09-25 10:29 UTC, Aloomenon commented on Lab1/src/App.java
>  public class App {
Убедитесь, что освобождаете все ресурсы.

2020-09-25 10:33 UTC, Dross0 commented
У меня есть дефолтные значения для этих параметров

2020-09-25 10:40 UTC, Dross0 commented
VM при terminate освободит все ресурсы

2020-09-25 10:43 UTC, Dross0 commented on Lab1/src/App.java
>  public class App {
Я как понимаю это про файл конфигурации, я только его забыл закрыть

2020-09-25 10:53 UTC, Aloomenon commented
А если данные будут кривые?

2020-09-25 10:54 UTC, Aloomenon commented
Предоставьте пруфы в виде спеки, или официальной документации, что виртуальная машина при терминэйте освобождает все ресурсы.

2020-09-25 11:13 UTC, Dross0 commented
Я считаю, что она освобождает, если хотите я могу shutdownHook повесить, чтобы уж на 100% освободила, хотя я не вижу в этом необходимости

2020-09-25 13:44 UTC, Aloomenon commented
Ну почему же. Jvm, с ваших слов, освобождает ресурсы при terminate. Дайте мне пруфы.
P.S. ваше личное мнение - не пруф.

2020-09-25 13:58 UTC, Dross0 commented
"Я считаю" - я имел ввиду, что я читал об этом, но искать прям пруф в доках нет сильного желания и чтобы гарантировать закрытие могу добавить хук, но как я понимаю, тогда прога уже не будет однопоточной))) По той же причине я закомментировал вариант с таймером

2020-09-25 14:02 UTC, Aloomenon commented
Хук спасет вас от экстренного завершения программы?

2020-09-25 14:04 UTC, Dross0 commented
От завершения программы - да, от завершения JVM - нет

2020-09-25 14:08 UTC, Aloomenon commented
Sigkill поймает?

2020-09-25 14:09 UTC, Dross0 commented
Нет

2020-09-25 14:10 UTC, Dross0 commented
Все сигналы, кроме SIGKILL

2020-09-26 04:27 UTC, Aloomenon commented
Окей, принял

2020-10-04 07:28 UTC, merged