Lab 3 - Chat
Dross0/Network-Labs pull request #4
Opened 2020-11-10 09:08 UTC by Dross0

@Aloomenon

2020-11-14 09:00 UTC, Aloomenon requested changes

2020-11-14 09:00 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/ChatNode.java
> +            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
какая кодировка используется?

2020-11-14 09:00 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/ChatNode.java
> +    private void checkExitCommand(String inputCommand) {
в этом случае InputStream закрывать не надо?

2020-11-14 09:00 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Это зачем?

2020-11-14 09:07 UTC, Dross0 commented on Lab3/src/main/java/chatnode/ChatNode.java
> +    private void checkExitCommand(String inputCommand) {
Не нужно, так как мы работаем с System.in, то мы закроем его просто по завершению чата, а я добавил метод close, чтобы клиент класса мог сам решить закрывать ли stream или нет

2020-11-14 09:10 UTC, Dross0 commented on Lab3/src/main/java/chatnode/ChatNode.java
> +            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
Укажу, пропустил

2020-11-14 14:54 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Если про if, то чтобы убрать Connect к самому себе

2020-11-14 14:56 UTC, Dross0 commented on Lab3/src/main/java/chatnode/ChatNode.java
> +            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));
Добавил

2020-11-15 21:12 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
нет, я про коннект.

2020-11-16 06:08 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Чтобы явно отделить стадию конекта, чтобы при каждом сообщении не вести проверку: это сообщение от нового соседа - или уже существующего.

2020-11-21 14:29 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Тогда еще сделайте аутентификацию ноды. Кейс такой: У ноды отрубилось питание. В сети появляется устройство с таким же ip, как и у прошлой ноды. По тому же порту она подключается к другому родителю.

2020-11-21 14:29 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Это я к тому, что раз у вас есть подключение, вы должны давать гарантию, что общаетесь с тем же самым узлом.

2020-11-21 15:28 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Так и что, нода отвалится, удалится из списка соседей, и уже новая нода с тем же ip будет расцениваться как новый пользователь чата

2020-11-21 15:31 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Если убрать конент, то мы просто свалим проверки из конекта на другой тип сообщения, что не так уж и хорошо соответсвует SRP

2020-11-21 15:36 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
И Connect я назвал так потому что такой вид сообщений является более понятным, хотя по сути я могу просто переименовать этот тип сообщений как ADD_ME_AT_NEIGHBORS. Само соединение по факту не происходит (как в TCP), это просто запрос на то чтобы нода добавила отправителя в список соседей

2020-11-24 07:09 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Окей, оставляйте проверку, если хотите, но гарантируете верную работу следующего кейса: нода 1 подключается к ноде 2(которая подключена к ноде 4). У ноды 1 отключается свет. В это время подключается нода 3 с таким же ИП и портом, но уже к ноде 4. Может ли 2 нода считать своим соседом ноду 1?

2020-11-24 07:33 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
У нас есть AliveMessage, если от ноды некоторый фиксированный период они не поступают, то сосед удаляется из списка соседей.

2020-11-24 19:11 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
у вас получается фиксированный период - время подключения непонятно какое поведение. Негоже!

2020-11-24 19:12 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Да и причем тут SRP, я вообще не понимаю.

2020-11-25 07:26 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
SRP потому что на кого нам сложить добавление соседа: если на TextMessgae, то нова к которой подключаются не сможет общаться с подключённым соседом, пока тот не отправит текстовое сообщение, если на AliveMessage, то складывать проверку на добавление соседа на ping сообщения, я считаю такая себе практика, так как список соседей всем нужен, то по нему нужна синхронизация или структуры данных обеспечивающие ее, а это все относительно дорогие операции для столь частых событий как ping message. И я вообще не вижу как удаление коннекта решает проблему аутентификации, потому что это просто перекидывание функций добавления соседа на другой тип сообщений.

2020-11-25 07:42 UTC, Aloomenon commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Если вы не реализовываете подключение, вам не нужно заботиться об аутентификации ноды. Т.к. вашей ноде должно быть вообще без разницы, кто ей шлёт сообщение. Пинг тоже не нужен, а уж синхронизация списков соседей и подавно.

2020-11-25 07:58 UTC, Dross0 commented on Lab3/src/main/java/chatnode/MessageReceiver.java
> +                    case CONNECT:
Окей, чем спорить, я могу переделать, но я не сильно согласен

2020-11-30 13:16 UTC, Aloomenon commented
ок принял

2020-11-30 16:38 UTC, merged