Lab4
Dross0/Network-Labs pull request #5
Opened 2020-12-07 13:28 UTC by Dross0

Finish snake. @Aloomenon

2020-12-14 10:33 UTC, Aloomenon requested changes
Закрывайте ресурсы.
Что гарантирует, что не слетит кодировка сообщений при сериализации\десериализации через SerializationUtils ?

2020-12-15 05:09 UTC, Dross0 commented
@Aloomenon, Добавил таймауты на сокеты для получения, чтобы при выходе все точно завершалось, ну и при исключениях добавил закрытие. 
А почему она может слететь? SerializationUtils это просто обертка над ByteArrayOutputStream/ByteArrayInputStream предоставляющая простой и удобный интерфейс для сериализации не в ObjectStream, а в массив.

2020-12-16 20:27 UTC, Aloomenon commented
если я приконекчусь к вам и у меня будет кодировка cp1251, к чему это может привести?

2020-12-17 09:54 UTC, Dross0 commented
@Aloomenon, Добавил кодировку в сообщения

2020-12-17 09:55 UTC, Aloomenon approved these changes
Принял

2020-12-17 09:59 UTC, merged

2020-12-17 09:59 UTC, Dross0 commented
Хорошо, спасибо